### ISSUE TITLE
Can not publish plugin to maven repo

### ISSUE THREAD

**Issue by zjinys** [informant-army/raven-grails#12]
There's a wrong section in BuildConfig.groovy, 

``` Groovy
dependencies {
        build("org.grails.plugins:tomcat:$grailsVersion",
              "org.grails.plugins:release:2.2.0",
              "org.grails.plugins:rest-client-builder:1.0.3") {
            export = false
        }
    }
```

which "dependencies" should be "plugins"

**Comment by alfakini** [comment]
Thanks for reporting this @zjinys Please update your local repository and do the grails package-plugin again. I updated the plugin version to 0.4.4. The plugin will be soon available at grailsCentral, I'm working on it :)
