### ISSUE TITLE
Tag support

### ISSUE THREAD

**Issue by alfakini** [informant-army/raven-grails#16]
Tags are key/value pairs that describe an event. They should be configurable in the following contexts:

Environment (client-level)
Thread (block-level)
Event (as part of capture)

Each of these should inherit its parent. So for example, if you configure your client as so:

client = Client(..., {
    'tags': {'foo': 'bar'},
})

And then you capture an event:

client.captureMessage('test', {
    'tags': {'foo': 'baz'},
})

The client should send the following usptream for tags:

{
    "tags": [
        ["foo", "bar"],
        ["foo", "baz"]
    ],
}

http://sentry.readthedocs.org/en/latest/developer/client/index.html#id1

**Comment by lesiki** [comment]
Maybe this could be broken down to issues for each tag scope?
- Environment (client-level)
- Thread (block-level)
- Event (as part of capture)

I think environment-level tag support isn't too big. @informant-army would you take a pull request for environment/client-level-only tag support?

**Comment by alfakini** [comment]
hey @lesiki Just to let you know, the repository moved to https://github.com/agorapulse/grails-raven
It would be nice to have environment-level tags implemented :+1:
