### ISSUE TITLE
Raven-java client

### ISSUE THREAD

**Issue by benorama** [informant-army/raven-grails#21]
Hi,

Too bad, I did not see your project, I was about to release our Sentry Grails Plugin next week ;).

I was wondering why you developed a groovy-based client from scratch and did not use the official raven-java client?

Thanks.

**Comment by alfakini** [comment]
Hey @benorama , if you read the commit history, you will see that we started using the raven-java 2 months ago. Actually, the Connection.groovy class is almost the same code written in a groovy way. The problem is that I don't like to have a jar dependency on the lib dir.

We could discuss about merging the two projects. I just would like to not have an embedded jar dependency, It would be great to have it versioned in a stable maven repository.

**Comment by benorama** [comment]
I understand your reason.
Did you use the master branch or the refactoring branch as source?

Next week, I hope to have some free time to see if I can submit some stuff.
I'll keep you informed.

Sentry is definitely one of the best of its kind.

**Comment by alfakini** [comment]
Hey @benorama Now I see that you're using a different branch in your project. The refactoring branch have a much better version of raven-java library.

I would really enjoy to work in the plugin with someone else and have the experience to develop a useful project in the open source distributed way. This plugin is my first attempt to do that. If you're interested, we could merge the two projects. I don't know how stable is the refactoring branch, but in terms of API it seems to be better than the master, we could keep it, in lib and try to deploy it to a stable maven repository (I don't know exactly how to do that :P). What do you think?

Cheers,
alf.

**Comment by benorama** [comment]
Hi Alf,

We are using the Sentry Raven Java client with our plugin in production since a week and everything works fine. The only interesting information missing is the OS/browser, I don't know why the user agent is not sent by raven java client.

Sure, we can try to merge the two projects.
I'll work on this later this week and I'll send you a github pull request so you can validate/merge the diff.

As for deploy the raven-java jar in a maven repo, we could a CloudBees repository.
I'll do it.

Ben

**Comment by alfakini** [comment]
I started a conversation here about deploying the raven-java to maven Central: https://github.com/kencochrane/raven-java/issues/32

**Comment by benorama** [comment]
Hi Alf,

Sorry for the late answer, we had some crazy work during those last weeks...
So, what is a the status on this?

Unfortunately, it looks like the Raven Java project is not very active...
So you might keep your implementation.

I'm going to try your plugin on one of our projects to see how it goes.

By the way, have you tried to use Raven JS to capture JS exception?

Ben
