### ISSUE TITLE
Async message with AsyncHTTPBuilder

### ISSUE THREAD

**Issue by benorama** [informant-army/raven-grails#23]
Hi,

I was wondering, it would be possible to send message asynchronously by default?
It would be better for performances.

This what we do in our KISSmetrics and Vero plugins, thanks to AsyncHTTPBuilder.

I've seen that you use native java HTTP URL/Connection.
Do you think that it would be a good idea to use HTTPBuilder and AsyncHTTPBuilder instead?

Ben

**Comment by alfakini** [comment]
Hey @benorama, I think that would be great to have async support and use HTTPBuilder/AsyncHTTPBuilder instead of the native java api.
